export const FUTURISTIC_COLORS = {
  primary: "#FFD700",
  secondary: "#FF00FF",
  accent: "#E91E63",
  background: ["#000000", "#0A0A0A", "#000000"] as const,
  cardBg: "rgba(20, 20, 20, 0.85)",
  cardBorder: "rgba(255, 215, 0, 0.3)",
  text: {
    primary: "#FFFFFF",
    secondary: "#FFD700",
    light: "#999999",
  },
  glow: "rgba(255, 215, 0, 0.4)",
  purple: "#FF00FF",
  pink: "#E91E63",
  green: "#FFD700",
  orange: "#FF00FF",
  morning: "#FFD700",
  night: "#FF00FF",
  selected: "#FFD700",
  today: "#FF00FF",
  error: "#E91E63",
  success: "#FFD700",
  warning: "#FF00FF",
  info: "#E91E63",
  border: "rgba(255, 215, 0, 0.3)",
};

export const FUTURISTIC_GRADIENTS = {
  primary: [FUTURISTIC_COLORS.primary, FUTURISTIC_COLORS.secondary] as const,
  secondary: [FUTURISTIC_COLORS.secondary, FUTURISTIC_COLORS.accent] as const,
  background: FUTURISTIC_COLORS.background,
  card: ["rgba(255, 215, 0, 0.1)", "rgba(255, 0, 255, 0.1)"] as const,
  button: [FUTURISTIC_COLORS.primary, FUTURISTIC_COLORS.secondary] as const,
  feature1: [FUTURISTIC_COLORS.primary, FUTURISTIC_COLORS.secondary] as const,
  feature2: [FUTURISTIC_COLORS.secondary, FUTURISTIC_COLORS.accent] as const,
  feature3: [FUTURISTIC_COLORS.accent, FUTURISTIC_COLORS.primary] as const,
  feature4: [FUTURISTIC_COLORS.primary, FUTURISTIC_COLORS.purple] as const,
  feature5: [FUTURISTIC_COLORS.pink, FUTURISTIC_COLORS.secondary] as const,
};
