import createContextHook from '@nkzw/create-context-hook';
import React, { useState, useEffect, useMemo, useCallback, useRef } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { encrypt, decrypt } from '@/utils/encryption';
import { Platform } from 'react-native';


export type Language = 'en' | 'es' | 'fr' | 'ar' | 'zh' | 'pt' | 'ja' | 'he' | 'ro' | 'ru' | 'hi' | 'it';

type TranslationKeys = {
  // Navigation & Tabs
  calendar: string;
  track: string;
  learn: string;
  settings: string;
  morning: string;
  night: string;
  phonebook: string;
  chats: string;
  planner: string;
  ai: string;
  universe: string;
  analytics: string;
  
  // Calendar
  thisMonth: string;
  events: string;
  high: string;
  medium: string;
  low: string;
  noEventsForThisDay: string;
  tapThePlusButtonToAddOne: string;
  addEvent: string;
  editEvent: string;
  eventTitle: string;
  category: string;
  priority: string;
  time: string;
  description: string;
  work: string;
  personal: string;
  health: string;
  social: string;
  other: string;
  updateEvent: string;
  deleteEvent: string;
  areYouSureDeleteEvent: string;
  cancel: string;
  delete: string;
  error: string;
  pleaseEnterEventTitle: string;
  addNotes: string;
  
  // Language Selection
  selectLanguage: string;
  chooseYourPreferredLanguage: string;
  continue: string;
  
  // Track Screen
  trackProgress: string;
  yourFinancialJourney: string;
  financialOverview: string;
  income: string;
  expenses: string;
  savings: string;
  netWorth: string;
  addTransaction: string;
  wealthManifesting: string;
  todaysManifestations: string;
  noManifestationsYet: string;
  addManifestation: string;
  wealthGoals: string;
  noWealthGoalsYet: string;
  addGoal: string;
  complete: string;
  metricsDashboard: string;
  trackAndAnalyze: string;
  passwordManager: string;
  secureVault: string;
  mindMapping: string;
  visualizeIdeas: string;
  
  // Morning Screen
  riseAndShine: string;
  goodMorning: string;
  seizeTheDay: string;
  morningInspiration: string;
  awakeningRituals: string;
  morningMeditation: string;
  centerYourMind: string;
  morningRoutines: string;
  buildYourPerfectRitual: string;
  dailyAffirmations: string;
  speakPowerIntoExistence: string;
  morningHabits: string;
  fuelYourTransformation: string;
  wellnessCheck: string;
  tuneIntoYourEnergy: string;
  embraceTheLight: string;
  
  // Night Screen
  goodEvening: string;
  goodNight: string;
  restWell: string;
  tonightsReflection: string;
  eveningRituals: string;
  momentsOfGratitude: string;
  captureYourThoughts: string;
  howImFeeling: string;
  checkInWithEmotions: string;
  dreamJournal: string;
  captureYourDreams: string;
  sleepMeditation: string;
  peacefulRestSounds: string;
  tomorrowsIntentions: string;
  setGoalsForTomorrow: string;
  dailyHealthAssessment: string;
  takeYourTime: string;
  
  // Settings
  toolsAndSettings: string;
  customizeYourExperience: string;
  membership: string;
  premiumPlan: string;
  activeSubscription: string;
  accountSettings: string;
  manageYourAccount: string;
  appTour: string;
  watchVideoTour: string;
  notifications: string;
  manageEventReminders: string;
  nightMode: string;
  enabled: string;
  disabled: string;
  theme: string;
  language: string;
  audioStyle: string;
  sound: string;
  muted: string;
  unavailable: string;
  textSize: string;
  appMode: string;
  universeMode: string;
  classicMode: string;
  logOut: string;
  signedInWithDemo: string;
  verified: string;
  autoTheme: string;
  autoThemeDescription: string;
  calendarBackgrounds: string;
  customizeCalendarAppearance: string;
  calendarThemes: string;
  yourCalendars: string;
  colorThemes: string;
  themesAvailable: string;
  backToTools: string;
  choosePreferredAudioStyle: string;
  chooseComfortableSize: string;
  customizeAppAppearance: string;
  name: string;
  email: string;
  account: string;
  
  // Forms
  title: string;
  amount: string;
  type: string;
  goalTitle: string;
  targetAmount: string;
  manifestation: string;
  writeYourManifestation: string;
  amountOptional: string;
  
  // Common
  save: string;
  edit: string;
  add: string;
  close: string;
  back: string;
  next: string;
  done: string;
  loading: string;
  success: string;
  pleaseWait: string;
  noDataYet: string;
  tapToAdd: string;
  shared: string;
  active: string;
  level: string;
  dayStreak: string;
  completed: string;
  badges: string;
  xp: string;
};

const translations: Record<Language, TranslationKeys> = {
  en: {
    // Navigation & Tabs
    calendar: 'Calendar',
    track: 'Track',
    learn: 'Learn',
    settings: 'Settings',
    morning: 'Morning',
    night: 'Night',
    phonebook: 'Contacts',
    chats: 'Chats',
    planner: 'Planner',
    ai: 'AI',
    universe: 'Universe',
    analytics: 'Analytics',
    
    // Calendar
    thisMonth: 'This Month',
    events: 'Events',
    high: 'High',
    medium: 'Medium',
    low: 'Low',
    noEventsForThisDay: 'No events for this day',
    tapThePlusButtonToAddOne: 'Tap the + button to add one',
    addEvent: 'Add Event',
    editEvent: 'Edit Event',
    eventTitle: 'Event Title',
    category: 'Category',
    priority: 'Priority',
    time: 'Time',
    description: 'Description',
    work: 'Work',
    personal: 'Personal',
    health: 'Health',
    social: 'Social',
    other: 'Other',
    updateEvent: 'Update Event',
    deleteEvent: 'Delete Event',
    areYouSureDeleteEvent: 'Are you sure you want to delete this event?',
    cancel: 'Cancel',
    delete: 'Delete',
    error: 'Error',
    pleaseEnterEventTitle: 'Please enter an event title',
    addNotes: 'Add notes...',
    
    // Language Selection
    selectLanguage: 'Select Language',
    chooseYourPreferredLanguage: 'Choose your preferred language',
    continue: 'Continue',
    
    // Track Screen
    trackProgress: 'Track Progress',
    yourFinancialJourney: 'Your Financial Journey',
    financialOverview: 'Financial Overview',
    income: 'Income',
    expenses: 'Expenses',
    savings: 'Savings',
    netWorth: 'Net Worth',
    addTransaction: 'Add Transaction',
    wealthManifesting: 'Wealth Manifesting',
    todaysManifestations: "Today's Manifestations",
    noManifestationsYet: 'No manifestations yet today',
    addManifestation: 'Add Manifestation',
    wealthGoals: 'Wealth Goals',
    noWealthGoalsYet: 'No wealth goals yet',
    addGoal: 'Add Goal',
    complete: 'Complete',
    metricsDashboard: 'Metrics Dashboard',
    trackAndAnalyze: 'Track & Analyze',
    passwordManager: 'Password Manager',
    secureVault: 'Secure Vault',
    mindMapping: 'Mind Mapping',
    visualizeIdeas: 'Visualize Ideas',
    
    // Morning Screen
    riseAndShine: 'Rise & Shine',
    goodMorning: 'Good Morning',
    seizeTheDay: 'Seize the Day',
    morningInspiration: 'Morning Inspiration',
    awakeningRituals: 'Awakening Rituals',
    morningMeditation: 'Morning Meditation',
    centerYourMind: 'Center your mind & breathe',
    morningRoutines: 'Morning Routines',
    buildYourPerfectRitual: 'Build your perfect ritual',
    dailyAffirmations: 'Daily Affirmations',
    speakPowerIntoExistence: 'Speak power into existence',
    morningHabits: 'Morning Habits',
    fuelYourTransformation: 'Fuel your transformation',
    wellnessCheck: 'Wellness Check',
    tuneIntoYourEnergy: 'Tune into your energy',
    embraceTheLight: 'Embrace the light. Own your day.',
    
    // Night Screen
    goodEvening: 'Good Evening',
    goodNight: 'Good Night',
    restWell: 'Rest Well',
    tonightsReflection: "Tonight's Reflection",
    eveningRituals: 'Evening Rituals',
    momentsOfGratitude: 'Moments of Gratitude',
    captureYourThoughts: 'Capture your thoughts',
    howImFeeling: "How I'm Feeling",
    checkInWithEmotions: 'Check in with your emotions',
    dreamJournal: 'Dream Journal',
    captureYourDreams: 'Capture your dreams',
    sleepMeditation: 'Sleep Meditation',
    peacefulRestSounds: 'Peaceful rest sounds',
    tomorrowsIntentions: "Tomorrow's Intentions",
    setGoalsForTomorrow: 'Set goals for tomorrow',
    dailyHealthAssessment: 'Daily health assessment',
    takeYourTime: "Take your time. There's no rush.",
    
    // Settings
    toolsAndSettings: 'Tools & Settings',
    customizeYourExperience: 'Customize your experience',
    membership: 'Membership',
    premiumPlan: 'Premium Plan',
    activeSubscription: 'Active subscription',
    accountSettings: 'Account Settings',
    manageYourAccount: 'Manage your account information',
    appTour: 'App Tour',
    watchVideoTour: "Watch video tour & listen to Audrey's song",
    notifications: 'Notifications',
    manageEventReminders: 'Manage event reminders',
    nightMode: 'Night Mode',
    enabled: 'Enabled',
    disabled: 'Disabled',
    theme: 'Theme',
    language: 'Language',
    audioStyle: 'Audio Style',
    sound: 'Sound',
    muted: 'Muted',
    unavailable: 'Unavailable',
    textSize: 'Text Size',
    appMode: 'App Mode',
    universeMode: 'Universe Mode',
    classicMode: 'Classic Mode',
    logOut: 'Log Out',
    signedInWithDemo: 'You are signed in with a demo account',
    verified: 'Verified',
    autoTheme: 'Auto Theme',
    autoThemeDescription: 'Automatically change theme based on holidays and seasons',
    calendarBackgrounds: 'Calendar Backgrounds',
    customizeCalendarAppearance: 'Customize your calendar appearance',
    calendarThemes: 'Calendar Themes',
    yourCalendars: 'Your calendars',
    colorThemes: 'Color Themes',
    themesAvailable: 'themes available',
    backToTools: 'Back to Tools',
    choosePreferredAudioStyle: 'Choose your preferred audio style',
    chooseComfortableSize: 'Choose a comfortable reading size',
    customizeAppAppearance: 'Customize your app appearance',
    name: 'Name',
    email: 'Email',
    account: 'Account',
    
    // Forms
    title: 'Title',
    amount: 'Amount',
    type: 'Type',
    goalTitle: 'Goal Title',
    targetAmount: 'Target Amount',
    manifestation: 'Manifestation',
    writeYourManifestation: 'Write your manifestation...',
    amountOptional: 'Amount (Optional)',
    
    // Common
    save: 'Save',
    edit: 'Edit',
    add: 'Add',
    close: 'Close',
    back: 'Back',
    next: 'Next',
    done: 'Done',
    loading: 'Loading...',
    success: 'Success',
    pleaseWait: 'Please wait...',
    noDataYet: 'No data yet',
    tapToAdd: 'Tap to add',
    shared: 'Shared',
    active: 'Active',
    level: 'Level',
    dayStreak: 'day streak',
    completed: 'completed',
    badges: 'badges',
    xp: 'XP',
  },
  es: {
    calendar: 'Calendario',
    track: 'Seguir',
    learn: 'Aprender',
    settings: 'Ajustes',
    morning: 'Mañana',
    night: 'Noche',
    phonebook: 'Contactos',
    chats: 'Chats',
    planner: 'Planificador',
    ai: 'IA',
    universe: 'Universo',
    analytics: 'Análisis',
    thisMonth: 'Este Mes',
    events: 'Eventos',
    high: 'Alta',
    medium: 'Media',
    low: 'Baja',
    noEventsForThisDay: 'No hay eventos para este día',
    tapThePlusButtonToAddOne: 'Toca el botón + para agregar uno',
    addEvent: 'Agregar Evento',
    editEvent: 'Editar Evento',
    eventTitle: 'Título del Evento',
    category: 'Categoría',
    priority: 'Prioridad',
    time: 'Hora',
    description: 'Descripción',
    work: 'Trabajo',
    personal: 'Personal',
    health: 'Salud',
    social: 'Social',
    other: 'Otro',
    updateEvent: 'Actualizar Evento',
    deleteEvent: 'Eliminar Evento',
    areYouSureDeleteEvent: '¿Estás seguro de que quieres eliminar este evento?',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    error: 'Error',
    pleaseEnterEventTitle: 'Por favor ingresa un título de evento',
    addNotes: 'Agregar notas...',
    selectLanguage: 'Seleccionar Idioma',
    chooseYourPreferredLanguage: 'Elige tu idioma preferido',
    continue: 'Continuar',
    trackProgress: 'Seguir Progreso',
    yourFinancialJourney: 'Tu Viaje Financiero',
    financialOverview: 'Resumen Financiero',
    income: 'Ingresos',
    expenses: 'Gastos',
    savings: 'Ahorros',
    netWorth: 'Patrimonio Neto',
    addTransaction: 'Agregar Transacción',
    wealthManifesting: 'Manifestación de Riqueza',
    todaysManifestations: 'Manifestaciones de Hoy',
    noManifestationsYet: 'Sin manifestaciones hoy',
    addManifestation: 'Agregar Manifestación',
    wealthGoals: 'Metas de Riqueza',
    noWealthGoalsYet: 'Sin metas de riqueza',
    addGoal: 'Agregar Meta',
    complete: 'Completar',
    metricsDashboard: 'Panel de Métricas',
    trackAndAnalyze: 'Seguir y Analizar',
    passwordManager: 'Gestor de Contraseñas',
    secureVault: 'Bóveda Segura',
    mindMapping: 'Mapas Mentales',
    visualizeIdeas: 'Visualizar Ideas',
    riseAndShine: 'Levántate y Brilla',
    goodMorning: 'Buenos Días',
    seizeTheDay: 'Aprovecha el Día',
    morningInspiration: 'Inspiración Matutina',
    awakeningRituals: 'Rituales de Despertar',
    morningMeditation: 'Meditación Matutina',
    centerYourMind: 'Centra tu mente y respira',
    morningRoutines: 'Rutinas Matutinas',
    buildYourPerfectRitual: 'Construye tu ritual perfecto',
    dailyAffirmations: 'Afirmaciones Diarias',
    speakPowerIntoExistence: 'Habla poder a la existencia',
    morningHabits: 'Hábitos Matutinos',
    fuelYourTransformation: 'Impulsa tu transformación',
    wellnessCheck: 'Control de Bienestar',
    tuneIntoYourEnergy: 'Sintoniza con tu energía',
    embraceTheLight: 'Abraza la luz. Adueñate de tu día.',
    goodEvening: 'Buenas Tardes',
    goodNight: 'Buenas Noches',
    restWell: 'Descansa Bien',
    tonightsReflection: 'Reflexión de Esta Noche',
    eveningRituals: 'Rituales Nocturnos',
    momentsOfGratitude: 'Momentos de Gratitud',
    captureYourThoughts: 'Captura tus pensamientos',
    howImFeeling: 'Cómo Me Siento',
    checkInWithEmotions: 'Conecta con tus emociones',
    dreamJournal: 'Diario de Sueños',
    captureYourDreams: 'Captura tus sueños',
    sleepMeditation: 'Meditación para Dormir',
    peacefulRestSounds: 'Sonidos de descanso',
    tomorrowsIntentions: 'Intenciones para Mañana',
    setGoalsForTomorrow: 'Establece metas para mañana',
    dailyHealthAssessment: 'Evaluación de salud diaria',
    takeYourTime: 'Tómate tu tiempo. No hay prisa.',
    toolsAndSettings: 'Herramientas y Ajustes',
    customizeYourExperience: 'Personaliza tu experiencia',
    membership: 'Membresía',
    premiumPlan: 'Plan Premium',
    activeSubscription: 'Suscripción activa',
    accountSettings: 'Configuración de Cuenta',
    manageYourAccount: 'Administra tu información de cuenta',
    appTour: 'Tour de la App',
    watchVideoTour: 'Ver video tour y escuchar la canción de Audrey',
    notifications: 'Notificaciones',
    manageEventReminders: 'Administrar recordatorios',
    nightMode: 'Modo Nocturno',
    enabled: 'Activado',
    disabled: 'Desactivado',
    theme: 'Tema',
    language: 'Idioma',
    audioStyle: 'Estilo de Audio',
    sound: 'Sonido',
    muted: 'Silenciado',
    unavailable: 'No disponible',
    textSize: 'Tamaño de Texto',
    appMode: 'Modo de App',
    universeMode: 'Modo Universo',
    classicMode: 'Modo Clásico',
    logOut: 'Cerrar Sesión',
    signedInWithDemo: 'Has iniciado sesión con una cuenta demo',
    verified: 'Verificado',
    autoTheme: 'Tema Automático',
    autoThemeDescription: 'Cambiar tema automáticamente según festividades y estaciones',
    calendarBackgrounds: 'Fondos de Calendario',
    customizeCalendarAppearance: 'Personaliza la apariencia del calendario',
    calendarThemes: 'Temas de Calendario',
    yourCalendars: 'Tus calendarios',
    colorThemes: 'Temas de Color',
    themesAvailable: 'temas disponibles',
    backToTools: 'Volver a Herramientas',
    choosePreferredAudioStyle: 'Elige tu estilo de audio preferido',
    chooseComfortableSize: 'Elige un tamaño de lectura cómodo',
    customizeAppAppearance: 'Personaliza la apariencia de la app',
    name: 'Nombre',
    email: 'Correo',
    account: 'Cuenta',
    title: 'Título',
    amount: 'Cantidad',
    type: 'Tipo',
    goalTitle: 'Título de la Meta',
    targetAmount: 'Cantidad Objetivo',
    manifestation: 'Manifestación',
    writeYourManifestation: 'Escribe tu manifestación...',
    amountOptional: 'Cantidad (Opcional)',
    save: 'Guardar',
    edit: 'Editar',
    add: 'Agregar',
    close: 'Cerrar',
    back: 'Atrás',
    next: 'Siguiente',
    done: 'Hecho',
    loading: 'Cargando...',
    success: 'Éxito',
    pleaseWait: 'Por favor espera...',
    noDataYet: 'Sin datos aún',
    tapToAdd: 'Toca para agregar',
    shared: 'Compartido',
    active: 'Activo',
    level: 'Nivel',
    dayStreak: 'días seguidos',
    completed: 'completados',
    badges: 'insignias',
    xp: 'XP',
  },
  it: {
    calendar: 'Calendario',
    track: 'Traccia',
    learn: 'Impara',
    settings: 'Impostazioni',
    morning: 'Mattina',
    night: 'Notte',
    phonebook: 'Contatti',
    chats: 'Chat',
    planner: 'Pianificatore',
    ai: 'IA',
    universe: 'Universo',
    analytics: 'Analisi',
    thisMonth: 'Questo Mese',
    events: 'Eventi',
    high: 'Alta',
    medium: 'Media',
    low: 'Bassa',
    noEventsForThisDay: 'Nessun evento per questo giorno',
    tapThePlusButtonToAddOne: 'Tocca il pulsante + per aggiungerne uno',
    addEvent: 'Aggiungi Evento',
    editEvent: 'Modifica Evento',
    eventTitle: 'Titolo Evento',
    category: 'Categoria',
    priority: 'Priorità',
    time: 'Ora',
    description: 'Descrizione',
    work: 'Lavoro',
    personal: 'Personale',
    health: 'Salute',
    social: 'Sociale',
    other: 'Altro',
    updateEvent: 'Aggiorna Evento',
    deleteEvent: 'Elimina Evento',
    areYouSureDeleteEvent: 'Sei sicuro di voler eliminare questo evento?',
    cancel: 'Annulla',
    delete: 'Elimina',
    error: 'Errore',
    pleaseEnterEventTitle: "Inserisci un titolo per l'evento",
    addNotes: 'Aggiungi note...',
    selectLanguage: 'Seleziona Lingua',
    chooseYourPreferredLanguage: 'Scegli la tua lingua preferita',
    continue: 'Continua',
    trackProgress: 'Traccia Progressi',
    yourFinancialJourney: 'Il Tuo Viaggio Finanziario',
    financialOverview: 'Panoramica Finanziaria',
    income: 'Entrate',
    expenses: 'Spese',
    savings: 'Risparmi',
    netWorth: 'Patrimonio Netto',
    addTransaction: 'Aggiungi Transazione',
    wealthManifesting: 'Manifestazione della Ricchezza',
    todaysManifestations: 'Manifestazioni di Oggi',
    noManifestationsYet: 'Nessuna manifestazione oggi',
    addManifestation: 'Aggiungi Manifestazione',
    wealthGoals: 'Obiettivi di Ricchezza',
    noWealthGoalsYet: 'Nessun obiettivo di ricchezza',
    addGoal: 'Aggiungi Obiettivo',
    complete: 'Completa',
    metricsDashboard: 'Dashboard Metriche',
    trackAndAnalyze: 'Traccia e Analizza',
    passwordManager: 'Gestore Password',
    secureVault: 'Cassaforte Sicura',
    mindMapping: 'Mappe Mentali',
    visualizeIdeas: 'Visualizza Idee',
    riseAndShine: 'Alzati e Splendi',
    goodMorning: 'Buongiorno',
    seizeTheDay: 'Cogli il Giorno',
    morningInspiration: 'Ispirazione Mattutina',
    awakeningRituals: 'Rituali del Risveglio',
    morningMeditation: 'Meditazione Mattutina',
    centerYourMind: 'Centra la mente e respira',
    morningRoutines: 'Routine Mattutine',
    buildYourPerfectRitual: 'Costruisci il tuo rituale perfetto',
    dailyAffirmations: 'Affermazioni Giornaliere',
    speakPowerIntoExistence: "Parla potere all'esistenza",
    morningHabits: 'Abitudini Mattutine',
    fuelYourTransformation: 'Alimenta la tua trasformazione',
    wellnessCheck: 'Controllo Benessere',
    tuneIntoYourEnergy: 'Sintonizzati con la tua energia',
    embraceTheLight: 'Abbraccia la luce. Domina la giornata.',
    goodEvening: 'Buonasera',
    goodNight: 'Buonanotte',
    restWell: 'Riposa Bene',
    tonightsReflection: 'Riflessione di Stasera',
    eveningRituals: 'Rituali Serali',
    momentsOfGratitude: 'Momenti di Gratitudine',
    captureYourThoughts: 'Cattura i tuoi pensieri',
    howImFeeling: 'Come Mi Sento',
    checkInWithEmotions: 'Connettiti con le tue emozioni',
    dreamJournal: 'Diario dei Sogni',
    captureYourDreams: 'Cattura i tuoi sogni',
    sleepMeditation: 'Meditazione per Dormire',
    peacefulRestSounds: 'Suoni di riposo',
    tomorrowsIntentions: 'Intenzioni per Domani',
    setGoalsForTomorrow: 'Imposta obiettivi per domani',
    dailyHealthAssessment: 'Valutazione salute quotidiana',
    takeYourTime: 'Prenditi il tuo tempo. Non c\'è fretta.',
    toolsAndSettings: 'Strumenti e Impostazioni',
    customizeYourExperience: 'Personalizza la tua esperienza',
    membership: 'Abbonamento',
    premiumPlan: 'Piano Premium',
    activeSubscription: 'Abbonamento attivo',
    accountSettings: 'Impostazioni Account',
    manageYourAccount: 'Gestisci le informazioni del tuo account',
    appTour: 'Tour App',
    watchVideoTour: 'Guarda il video tour e ascolta la canzone di Audrey',
    notifications: 'Notifiche',
    manageEventReminders: 'Gestisci promemoria eventi',
    nightMode: 'Modalità Notte',
    enabled: 'Attivato',
    disabled: 'Disattivato',
    theme: 'Tema',
    language: 'Lingua',
    audioStyle: 'Stile Audio',
    sound: 'Suono',
    muted: 'Silenziato',
    unavailable: 'Non disponibile',
    textSize: 'Dimensione Testo',
    appMode: 'Modalità App',
    universeMode: 'Modalità Universo',
    classicMode: 'Modalità Classica',
    logOut: 'Esci',
    signedInWithDemo: 'Sei connesso con un account demo',
    verified: 'Verificato',
    autoTheme: 'Tema Automatico',
    autoThemeDescription: 'Cambia automaticamente tema in base a festività e stagioni',
    calendarBackgrounds: 'Sfondi Calendario',
    customizeCalendarAppearance: "Personalizza l'aspetto del calendario",
    calendarThemes: 'Temi Calendario',
    yourCalendars: 'I tuoi calendari',
    colorThemes: 'Temi Colore',
    themesAvailable: 'temi disponibili',
    backToTools: 'Torna agli Strumenti',
    choosePreferredAudioStyle: 'Scegli il tuo stile audio preferito',
    chooseComfortableSize: 'Scegli una dimensione di lettura comoda',
    customizeAppAppearance: "Personalizza l'aspetto dell'app",
    name: 'Nome',
    email: 'Email',
    account: 'Account',
    title: 'Titolo',
    amount: 'Importo',
    type: 'Tipo',
    goalTitle: "Titolo dell'Obiettivo",
    targetAmount: 'Importo Obiettivo',
    manifestation: 'Manifestazione',
    writeYourManifestation: 'Scrivi la tua manifestazione...',
    amountOptional: 'Importo (Opzionale)',
    save: 'Salva',
    edit: 'Modifica',
    add: 'Aggiungi',
    close: 'Chiudi',
    back: 'Indietro',
    next: 'Avanti',
    done: 'Fatto',
    loading: 'Caricamento...',
    success: 'Successo',
    pleaseWait: 'Attendere prego...',
    noDataYet: 'Nessun dato ancora',
    tapToAdd: 'Tocca per aggiungere',
    shared: 'Condiviso',
    active: 'Attivo',
    level: 'Livello',
    dayStreak: 'giorni consecutivi',
    completed: 'completati',
    badges: 'badge',
    xp: 'XP',
  },
  fr: {
    calendar: 'Calendrier',
    track: 'Suivre',
    learn: 'Apprendre',
    settings: 'Paramètres',
    morning: 'Matin',
    night: 'Nuit',
    phonebook: 'Contacts',
    chats: 'Discussions',
    planner: 'Planificateur',
    ai: 'IA',
    universe: 'Univers',
    analytics: 'Analytique',
    thisMonth: 'Ce Mois',
    events: 'Événements',
    high: 'Haute',
    medium: 'Moyenne',
    low: 'Basse',
    noEventsForThisDay: 'Aucun événement pour ce jour',
    tapThePlusButtonToAddOne: 'Appuyez sur le bouton + pour en ajouter un',
    addEvent: 'Ajouter un Événement',
    editEvent: 'Modifier l\'Événement',
    eventTitle: 'Titre de l\'Événement',
    category: 'Catégorie',
    priority: 'Priorité',
    time: 'Heure',
    description: 'Description',
    work: 'Travail',
    personal: 'Personnel',
    health: 'Santé',
    social: 'Social',
    other: 'Autre',
    updateEvent: 'Mettre à Jour l\'Événement',
    deleteEvent: 'Supprimer l\'Événement',
    areYouSureDeleteEvent: 'Êtes-vous sûr de vouloir supprimer cet événement?',
    cancel: 'Annuler',
    delete: 'Supprimer',
    error: 'Erreur',
    pleaseEnterEventTitle: 'Veuillez entrer un titre d\'événement',
    addNotes: 'Ajouter des notes...',
    selectLanguage: 'Sélectionner la Langue',
    chooseYourPreferredLanguage: 'Choisissez votre langue préférée',
    continue: 'Continuer',
    trackProgress: 'Suivre les Progrès',
    yourFinancialJourney: 'Votre Parcours Financier',
    financialOverview: 'Aperçu Financier',
    income: 'Revenus',
    expenses: 'Dépenses',
    savings: 'Économies',
    netWorth: 'Valeur Nette',
    addTransaction: 'Ajouter une Transaction',
    wealthManifesting: 'Manifestation de Richesse',
    todaysManifestations: 'Manifestations du Jour',
    noManifestationsYet: 'Aucune manifestation aujourd\'hui',
    addManifestation: 'Ajouter une Manifestation',
    wealthGoals: 'Objectifs de Richesse',
    noWealthGoalsYet: 'Aucun objectif de richesse',
    addGoal: 'Ajouter un Objectif',
    complete: 'Terminer',
    metricsDashboard: 'Tableau de Bord des Métriques',
    trackAndAnalyze: 'Suivre et Analyser',
    passwordManager: 'Gestionnaire de Mots de Passe',
    secureVault: 'Coffre-fort Sécurisé',
    mindMapping: 'Cartes Mentales',
    visualizeIdeas: 'Visualiser les Idées',
    riseAndShine: 'Lève-toi et Brille',
    goodMorning: 'Bonjour',
    seizeTheDay: 'Saisis le Jour',
    morningInspiration: 'Inspiration Matinale',
    awakeningRituals: 'Rituels d\'Éveil',
    morningMeditation: 'Méditation Matinale',
    centerYourMind: 'Centrez votre esprit et respirez',
    morningRoutines: 'Routines Matinales',
    buildYourPerfectRitual: 'Construisez votre rituel parfait',
    dailyAffirmations: 'Affirmations Quotidiennes',
    speakPowerIntoExistence: 'Parlez pouvoir à l\'existence',
    morningHabits: 'Habitudes Matinales',
    fuelYourTransformation: 'Alimentez votre transformation',
    wellnessCheck: 'Bilan de Bien-être',
    tuneIntoYourEnergy: 'Connectez-vous à votre énergie',
    embraceTheLight: 'Embrassez la lumière. Saisissez votre journée.',
    goodEvening: 'Bonsoir',
    goodNight: 'Bonne Nuit',
    restWell: 'Reposez-vous Bien',
    tonightsReflection: 'Réflexion de Ce Soir',
    eveningRituals: 'Rituels du Soir',
    momentsOfGratitude: 'Moments de Gratitude',
    captureYourThoughts: 'Capturez vos pensées',
    howImFeeling: 'Comment Je Me Sens',
    checkInWithEmotions: 'Connectez-vous à vos émotions',
    dreamJournal: 'Journal des Rêves',
    captureYourDreams: 'Capturez vos rêves',
    sleepMeditation: 'Méditation pour Dormir',
    peacefulRestSounds: 'Sons de repos paisible',
    tomorrowsIntentions: 'Intentions pour Demain',
    setGoalsForTomorrow: 'Fixez des objectifs pour demain',
    dailyHealthAssessment: 'Évaluation de santé quotidienne',
    takeYourTime: 'Prenez votre temps. Pas de précipitation.',
    toolsAndSettings: 'Outils et Paramètres',
    customizeYourExperience: 'Personnalisez votre expérience',
    membership: 'Adhésion',
    premiumPlan: 'Plan Premium',
    activeSubscription: 'Abonnement actif',
    accountSettings: 'Paramètres du Compte',
    manageYourAccount: 'Gérez les informations de votre compte',
    appTour: 'Visite de l\'App',
    watchVideoTour: 'Regarder la visite vidéo et écouter la chanson d\'Audrey',
    notifications: 'Notifications',
    manageEventReminders: 'Gérer les rappels d\'événements',
    nightMode: 'Mode Nuit',
    enabled: 'Activé',
    disabled: 'Désactivé',
    theme: 'Thème',
    language: 'Langue',
    audioStyle: 'Style Audio',
    sound: 'Son',
    muted: 'Muet',
    unavailable: 'Indisponible',
    textSize: 'Taille du Texte',
    appMode: 'Mode de l\'App',
    universeMode: 'Mode Univers',
    classicMode: 'Mode Classique',
    logOut: 'Se Déconnecter',
    signedInWithDemo: 'Vous êtes connecté avec un compte démo',
    verified: 'Vérifié',
    autoTheme: 'Thème Automatique',
    autoThemeDescription: 'Changer automatiquement le thème selon les fêtes et saisons',
    calendarBackgrounds: 'Arrière-plans du Calendrier',
    customizeCalendarAppearance: 'Personnalisez l\'apparence du calendrier',
    calendarThemes: 'Thèmes du Calendrier',
    yourCalendars: 'Vos calendriers',
    colorThemes: 'Thèmes de Couleur',
    themesAvailable: 'thèmes disponibles',
    backToTools: 'Retour aux Outils',
    choosePreferredAudioStyle: 'Choisissez votre style audio préféré',
    chooseComfortableSize: 'Choisissez une taille de lecture confortable',
    customizeAppAppearance: 'Personnalisez l\'apparence de l\'app',
    name: 'Nom',
    email: 'Email',
    account: 'Compte',
    title: 'Titre',
    amount: 'Montant',
    type: 'Type',
    goalTitle: 'Titre de l\'Objectif',
    targetAmount: 'Montant Cible',
    manifestation: 'Manifestation',
    writeYourManifestation: 'Écrivez votre manifestation...',
    amountOptional: 'Montant (Optionnel)',
    save: 'Enregistrer',
    edit: 'Modifier',
    add: 'Ajouter',
    close: 'Fermer',
    back: 'Retour',
    next: 'Suivant',
    done: 'Terminé',
    loading: 'Chargement...',
    success: 'Succès',
    pleaseWait: 'Veuillez patienter...',
    noDataYet: 'Pas encore de données',
    tapToAdd: 'Appuyez pour ajouter',
    shared: 'Partagé',
    active: 'Actif',
    level: 'Niveau',
    dayStreak: 'jours consécutifs',
    completed: 'terminés',
    badges: 'badges',
    xp: 'XP',
  },
  ar: {
    calendar: 'التقويم',
    track: 'تتبع',
    learn: 'تعلم',
    settings: 'الإعدادات',
    morning: 'الصباح',
    night: 'الليل',
    phonebook: 'جهات الاتصال',
    chats: 'المحادثات',
    planner: 'المخطط',
    ai: 'الذكاء الاصطناعي',
    universe: 'الكون',
    analytics: 'التحليلات',
    thisMonth: 'هذا الشهر',
    events: 'الأحداث',
    high: 'عالية',
    medium: 'متوسطة',
    low: 'منخفضة',
    noEventsForThisDay: 'لا توجد أحداث لهذا اليوم',
    tapThePlusButtonToAddOne: 'اضغط على زر + لإضافة واحد',
    addEvent: 'إضافة حدث',
    editEvent: 'تعديل الحدث',
    eventTitle: 'عنوان الحدث',
    category: 'الفئة',
    priority: 'الأولوية',
    time: 'الوقت',
    description: 'الوصف',
    work: 'عمل',
    personal: 'شخصي',
    health: 'صحة',
    social: 'اجتماعي',
    other: 'آخر',
    updateEvent: 'تحديث الحدث',
    deleteEvent: 'حذف الحدث',
    areYouSureDeleteEvent: 'هل أنت متأكد أنك تريد حذف هذا الحدث؟',
    cancel: 'إلغاء',
    delete: 'حذف',
    error: 'خطأ',
    pleaseEnterEventTitle: 'الرجاء إدخال عنوان الحدث',
    addNotes: 'أضف ملاحظات...',
    selectLanguage: 'اختر اللغة',
    chooseYourPreferredLanguage: 'اختر لغتك المفضلة',
    continue: 'متابعة',
    trackProgress: 'تتبع التقدم',
    yourFinancialJourney: 'رحلتك المالية',
    financialOverview: 'نظرة مالية عامة',
    income: 'الدخل',
    expenses: 'المصروفات',
    savings: 'المدخرات',
    netWorth: 'صافي الثروة',
    addTransaction: 'إضافة معاملة',
    wealthManifesting: 'تجلي الثروة',
    todaysManifestations: 'تجليات اليوم',
    noManifestationsYet: 'لا توجد تجليات اليوم',
    addManifestation: 'إضافة تجلي',
    wealthGoals: 'أهداف الثروة',
    noWealthGoalsYet: 'لا توجد أهداف ثروة',
    addGoal: 'إضافة هدف',
    complete: 'إكمال',
    metricsDashboard: 'لوحة المقاييس',
    trackAndAnalyze: 'تتبع وتحليل',
    passwordManager: 'مدير كلمات المرور',
    secureVault: 'خزنة آمنة',
    mindMapping: 'الخرائط الذهنية',
    visualizeIdeas: 'تصور الأفكار',
    riseAndShine: 'استيقظ وتألق',
    goodMorning: 'صباح الخير',
    seizeTheDay: 'اغتنم اليوم',
    morningInspiration: 'إلهام الصباح',
    awakeningRituals: 'طقوس الاستيقاظ',
    morningMeditation: 'تأمل الصباح',
    centerYourMind: 'ركز عقلك وتنفس',
    morningRoutines: 'روتين الصباح',
    buildYourPerfectRitual: 'ابنِ طقسك المثالي',
    dailyAffirmations: 'التأكيدات اليومية',
    speakPowerIntoExistence: 'انطق القوة للوجود',
    morningHabits: 'عادات الصباح',
    fuelYourTransformation: 'غذِّ تحولك',
    wellnessCheck: 'فحص العافية',
    tuneIntoYourEnergy: 'اتصل بطاقتك',
    embraceTheLight: 'احتضن النور. امتلك يومك.',
    goodEvening: 'مساء الخير',
    goodNight: 'تصبح على خير',
    restWell: 'ارتح جيداً',
    tonightsReflection: 'تأمل الليلة',
    eveningRituals: 'طقوس المساء',
    momentsOfGratitude: 'لحظات الامتنان',
    captureYourThoughts: 'سجل أفكارك',
    howImFeeling: 'كيف أشعر',
    checkInWithEmotions: 'تواصل مع مشاعرك',
    dreamJournal: 'دفتر الأحلام',
    captureYourDreams: 'سجل أحلامك',
    sleepMeditation: 'تأمل النوم',
    peacefulRestSounds: 'أصوات راحة هادئة',
    tomorrowsIntentions: 'نوايا الغد',
    setGoalsForTomorrow: 'حدد أهداف الغد',
    dailyHealthAssessment: 'تقييم الصحة اليومي',
    takeYourTime: 'خذ وقتك. لا استعجال.',
    toolsAndSettings: 'الأدوات والإعدادات',
    customizeYourExperience: 'خصص تجربتك',
    membership: 'العضوية',
    premiumPlan: 'الخطة المميزة',
    activeSubscription: 'اشتراك نشط',
    accountSettings: 'إعدادات الحساب',
    manageYourAccount: 'إدارة معلومات حسابك',
    appTour: 'جولة التطبيق',
    watchVideoTour: 'شاهد جولة الفيديو واستمع لأغنية أودري',
    notifications: 'الإشعارات',
    manageEventReminders: 'إدارة تذكيرات الأحداث',
    nightMode: 'الوضع الليلي',
    enabled: 'مفعل',
    disabled: 'معطل',
    theme: 'السمة',
    language: 'اللغة',
    audioStyle: 'نمط الصوت',
    sound: 'صوت',
    muted: 'صامت',
    unavailable: 'غير متوفر',
    textSize: 'حجم النص',
    appMode: 'وضع التطبيق',
    universeMode: 'وضع الكون',
    classicMode: 'الوضع الكلاسيكي',
    logOut: 'تسجيل الخروج',
    signedInWithDemo: 'أنت مسجل الدخول بحساب تجريبي',
    verified: 'موثق',
    autoTheme: 'سمة تلقائية',
    autoThemeDescription: 'تغيير السمة تلقائياً حسب المناسبات والمواسم',
    calendarBackgrounds: 'خلفيات التقويم',
    customizeCalendarAppearance: 'خصص مظهر التقويم',
    calendarThemes: 'سمات التقويم',
    yourCalendars: 'تقويماتك',
    colorThemes: 'سمات الألوان',
    themesAvailable: 'سمات متاحة',
    backToTools: 'العودة للأدوات',
    choosePreferredAudioStyle: 'اختر نمط الصوت المفضل',
    chooseComfortableSize: 'اختر حجم قراءة مريح',
    customizeAppAppearance: 'خصص مظهر التطبيق',
    name: 'الاسم',
    email: 'البريد الإلكتروني',
    account: 'الحساب',
    title: 'العنوان',
    amount: 'المبلغ',
    type: 'النوع',
    goalTitle: 'عنوان الهدف',
    targetAmount: 'المبلغ المستهدف',
    manifestation: 'التجلي',
    writeYourManifestation: 'اكتب تجليك...',
    amountOptional: 'المبلغ (اختياري)',
    save: 'حفظ',
    edit: 'تعديل',
    add: 'إضافة',
    close: 'إغلاق',
    back: 'رجوع',
    next: 'التالي',
    done: 'تم',
    loading: 'جاري التحميل...',
    success: 'نجاح',
    pleaseWait: 'الرجاء الانتظار...',
    noDataYet: 'لا توجد بيانات بعد',
    tapToAdd: 'اضغط للإضافة',
    shared: 'مشترك',
    active: 'نشط',
    level: 'المستوى',
    dayStreak: 'أيام متتالية',
    completed: 'مكتمل',
    badges: 'شارات',
    xp: 'نقاط الخبرة',
  },
  zh: {
    calendar: '日历',
    track: '追踪',
    learn: '学习',
    settings: '设置',
    morning: '早晨',
    night: '夜晚',
    phonebook: '联系人',
    chats: '聊天',
    planner: '规划器',
    ai: '人工智能',
    universe: '宇宙',
    analytics: '分析',
    thisMonth: '本月',
    events: '事件',
    high: '高',
    medium: '中',
    low: '低',
    noEventsForThisDay: '今天没有事件',
    tapThePlusButtonToAddOne: '点击 + 按钮添加一个',
    addEvent: '添加事件',
    editEvent: '编辑事件',
    eventTitle: '事件标题',
    category: '类别',
    priority: '优先级',
    time: '时间',
    description: '描述',
    work: '工作',
    personal: '个人',
    health: '健康',
    social: '社交',
    other: '其他',
    updateEvent: '更新事件',
    deleteEvent: '删除事件',
    areYouSureDeleteEvent: '您确定要删除此事件吗？',
    cancel: '取消',
    delete: '删除',
    error: '错误',
    pleaseEnterEventTitle: '请输入事件标题',
    addNotes: '添加笔记...',
    selectLanguage: '选择语言',
    chooseYourPreferredLanguage: '选择您的首选语言',
    continue: '继续',
    trackProgress: '跟踪进度',
    yourFinancialJourney: '您的财务之旅',
    financialOverview: '财务概览',
    income: '收入',
    expenses: '支出',
    savings: '储蓄',
    netWorth: '净资产',
    addTransaction: '添加交易',
    wealthManifesting: '财富显化',
    todaysManifestations: '今日显化',
    noManifestationsYet: '今天还没有显化',
    addManifestation: '添加显化',
    wealthGoals: '财富目标',
    noWealthGoalsYet: '还没有财富目标',
    addGoal: '添加目标',
    complete: '完成',
    metricsDashboard: '指标仪表板',
    trackAndAnalyze: '跟踪与分析',
    passwordManager: '密码管理器',
    secureVault: '安全保险库',
    mindMapping: '思维导图',
    visualizeIdeas: '可视化想法',
    riseAndShine: '早起发光',
    goodMorning: '早上好',
    seizeTheDay: '把握今天',
    morningInspiration: '晚上灵感',
    awakeningRituals: '觉醒仪式',
    morningMeditation: '晚上冥想',
    centerYourMind: '平静心忧，深呼吸',
    morningRoutines: '晚上例程',
    buildYourPerfectRitual: '构建你的完美仪式',
    dailyAffirmations: '每日肯定',
    speakPowerIntoExistence: '说出力量，让它存在',
    morningHabits: '晚上习惯',
    fuelYourTransformation: '加油你的转变',
    wellnessCheck: '健康检查',
    tuneIntoYourEnergy: '调整你的能量',
    embraceTheLight: '拥抱光明。掌控你的一天。',
    goodEvening: '晚上好',
    goodNight: '晚安',
    restWell: '好好休息',
    tonightsReflection: '今晚的反思',
    eveningRituals: '晚间仪式',
    momentsOfGratitude: '感恩时刻',
    captureYourThoughts: '记录你的想法',
    howImFeeling: '我的感觉',
    checkInWithEmotions: '与情绪连接',
    dreamJournal: '梦境日记',
    captureYourDreams: '记录你的梦',
    sleepMeditation: '睡眠冥想',
    peacefulRestSounds: '宁静休息声',
    tomorrowsIntentions: '明天的意图',
    setGoalsForTomorrow: '设定明天的目标',
    dailyHealthAssessment: '每日健康评估',
    takeYourTime: '慢慢来。不着急。',
    toolsAndSettings: '工具和设置',
    customizeYourExperience: '自定义你的体验',
    membership: '会员',
    premiumPlan: '高级计划',
    activeSubscription: '活跃订阅',
    accountSettings: '账户设置',
    manageYourAccount: '管理您的账户信息',
    appTour: '应用导览',
    watchVideoTour: '观看视频导览并收听Audrey的歌',
    notifications: '通知',
    manageEventReminders: '管理事件提醒',
    nightMode: '夜间模式',
    enabled: '已启用',
    disabled: '已禁用',
    theme: '主题',
    language: '语言',
    audioStyle: '音频风格',
    sound: '声音',
    muted: '静音',
    unavailable: '不可用',
    textSize: '文字大小',
    appMode: '应用模式',
    universeMode: '宇宙模式',
    classicMode: '经典模式',
    logOut: '退出登录',
    signedInWithDemo: '您已使用演示账户登录',
    verified: '已验证',
    autoTheme: '自动主题',
    autoThemeDescription: '根据节日和季节自动更换主题',
    calendarBackgrounds: '日历背景',
    customizeCalendarAppearance: '自定义日历外观',
    calendarThemes: '日历主题',
    yourCalendars: '您的日历',
    colorThemes: '颜色主题',
    themesAvailable: '可用主题',
    backToTools: '返回工具',
    choosePreferredAudioStyle: '选择您喜欢的音频风格',
    chooseComfortableSize: '选择舒适的阅读大小',
    customizeAppAppearance: '自定义应用外观',
    name: '姓名',
    email: '电子邮件',
    account: '账户',
    title: '标题',
    amount: '金额',
    type: '类型',
    goalTitle: '目标标题',
    targetAmount: '目标金额',
    manifestation: '显化',
    writeYourManifestation: '写下你的显化...',
    amountOptional: '金额（可选）',
    save: '保存',
    edit: '编辑',
    add: '添加',
    close: '关闭',
    back: '返回',
    next: '下一步',
    done: '完成',
    loading: '加载中...',
    success: '成功',
    pleaseWait: '请稍候...',
    noDataYet: '暂无数据',
    tapToAdd: '点击添加',
    shared: '共享',
    active: '活跃',
    level: '等级',
    dayStreak: '连续天数',
    completed: '已完成',
    badges: '徽章',
    xp: '经验值',
  },
  pt: {
    calendar: 'Calendário',
    track: 'Rastrear',
    learn: 'Aprender',
    settings: 'Configurações',
    morning: 'Manhã',
    night: 'Noite',
    phonebook: 'Contatos',
    chats: 'Conversas',
    planner: 'Planejador',
    ai: 'IA',
    universe: 'Universo',
    analytics: 'Análises',
    thisMonth: 'Este Mês',
    events: 'Eventos',
    high: 'Alta',
    medium: 'Média',
    low: 'Baixa',
    noEventsForThisDay: 'Sem eventos para este dia',
    tapThePlusButtonToAddOne: 'Toque no botão + para adicionar um',
    addEvent: 'Adicionar Evento',
    editEvent: 'Editar Evento',
    eventTitle: 'Título do Evento',
    category: 'Categoria',
    priority: 'Prioridade',
    time: 'Hora',
    description: 'Descrição',
    work: 'Trabalho',
    personal: 'Pessoal',
    health: 'Saúde',
    social: 'Social',
    other: 'Outro',
    updateEvent: 'Atualizar Evento',
    deleteEvent: 'Excluir Evento',
    areYouSureDeleteEvent: 'Tem certeza de que deseja excluir este evento?',
    cancel: 'Cancelar',
    delete: 'Excluir',
    error: 'Erro',
    pleaseEnterEventTitle: 'Por favor, insira um título de evento',
    addNotes: 'Adicionar notas...',
    selectLanguage: 'Selecionar Idioma',
    chooseYourPreferredLanguage: 'Escolha seu idioma preferido',
    continue: 'Continuar',
    trackProgress: 'Acompanhar Progresso',
    yourFinancialJourney: 'Sua Jornada Financeira',
    financialOverview: 'Visão Financeira',
    income: 'Renda',
    expenses: 'Despesas',
    savings: 'Poupança',
    netWorth: 'Patrimônio Líquido',
    addTransaction: 'Adicionar Transação',
    wealthManifesting: 'Manifestação de Riqueza',
    todaysManifestations: 'Manifestações de Hoje',
    noManifestationsYet: 'Sem manifestações hoje',
    addManifestation: 'Adicionar Manifestação',
    wealthGoals: 'Metas de Riqueza',
    noWealthGoalsYet: 'Sem metas de riqueza',
    addGoal: 'Adicionar Meta',
    complete: 'Completar',
    metricsDashboard: 'Painel de Métricas',
    trackAndAnalyze: 'Rastrear e Analisar',
    passwordManager: 'Gerenciador de Senhas',
    secureVault: 'Cofre Seguro',
    mindMapping: 'Mapas Mentais',
    visualizeIdeas: 'Visualizar Ideias',
    riseAndShine: 'Levante e Brilhe',
    goodMorning: 'Bom Dia',
    seizeTheDay: 'Aproveite o Dia',
    morningInspiration: 'Inspiração Matinal',
    awakeningRituals: 'Rituais de Despertar',
    morningMeditation: 'Meditação Matinal',
    centerYourMind: 'Centralize sua mente e respire',
    morningRoutines: 'Rotinas Matinais',
    buildYourPerfectRitual: 'Construa seu ritual perfeito',
    dailyAffirmations: 'Afirmações Diárias',
    speakPowerIntoExistence: 'Fale poder à existência',
    morningHabits: 'Hábitos Matinais',
    fuelYourTransformation: 'Alimente sua transformação',
    wellnessCheck: 'Verificação de Bem-estar',
    tuneIntoYourEnergy: 'Sintonize com sua energia',
    embraceTheLight: 'Abrace a luz. Domine seu dia.',
    goodEvening: 'Boa Noite',
    goodNight: 'Boa Noite',
    restWell: 'Descanse Bem',
    tonightsReflection: 'Reflexão de Hoje',
    eveningRituals: 'Rituais Noturnos',
    momentsOfGratitude: 'Momentos de Gratidão',
    captureYourThoughts: 'Capture seus pensamentos',
    howImFeeling: 'Como Me Sinto',
    checkInWithEmotions: 'Conecte-se com suas emoções',
    dreamJournal: 'Diário de Sonhos',
    captureYourDreams: 'Capture seus sonhos',
    sleepMeditation: 'Meditação para Dormir',
    peacefulRestSounds: 'Sons de descanso',
    tomorrowsIntentions: 'Intenções para Amanhã',
    setGoalsForTomorrow: 'Defina metas para amanhã',
    dailyHealthAssessment: 'Avaliação diária de saúde',
    takeYourTime: 'Leve seu tempo. Não há pressa.',
    toolsAndSettings: 'Ferramentas e Configurações',
    customizeYourExperience: 'Personalize sua experiência',
    membership: 'Assinatura',
    premiumPlan: 'Plano Premium',
    activeSubscription: 'Assinatura ativa',
    accountSettings: 'Configurações da Conta',
    manageYourAccount: 'Gerencie as informações da sua conta',
    appTour: 'Tour do App',
    watchVideoTour: 'Assista o tour em vídeo e ouça a música da Audrey',
    notifications: 'Notificações',
    manageEventReminders: 'Gerenciar lembretes de eventos',
    nightMode: 'Modo Noturno',
    enabled: 'Ativado',
    disabled: 'Desativado',
    theme: 'Tema',
    language: 'Idioma',
    audioStyle: 'Estilo de Áudio',
    sound: 'Som',
    muted: 'Mudo',
    unavailable: 'Indisponível',
    textSize: 'Tamanho do Texto',
    appMode: 'Modo do App',
    universeMode: 'Modo Universo',
    classicMode: 'Modo Clássico',
    logOut: 'Sair',
    signedInWithDemo: 'Você está conectado com uma conta demo',
    verified: 'Verificado',
    autoTheme: 'Tema Automático',
    autoThemeDescription: 'Mudar tema automaticamente com base em feriados e estações',
    calendarBackgrounds: 'Fundos do Calendário',
    customizeCalendarAppearance: 'Personalize a aparência do calendário',
    calendarThemes: 'Temas do Calendário',
    yourCalendars: 'Seus calendários',
    colorThemes: 'Temas de Cores',
    themesAvailable: 'temas disponíveis',
    backToTools: 'Voltar às Ferramentas',
    choosePreferredAudioStyle: 'Escolha seu estilo de áudio preferido',
    chooseComfortableSize: 'Escolha um tamanho de leitura confortável',
    customizeAppAppearance: 'Personalize a aparência do app',
    name: 'Nome',
    email: 'Email',
    account: 'Conta',
    title: 'Título',
    amount: 'Valor',
    type: 'Tipo',
    goalTitle: 'Título da Meta',
    targetAmount: 'Valor Alvo',
    manifestation: 'Manifestação',
    writeYourManifestation: 'Escreva sua manifestação...',
    amountOptional: 'Valor (Opcional)',
    save: 'Salvar',
    edit: 'Editar',
    add: 'Adicionar',
    close: 'Fechar',
    back: 'Voltar',
    next: 'Próximo',
    done: 'Concluído',
    loading: 'Carregando...',
    success: 'Sucesso',
    pleaseWait: 'Por favor aguarde...',
    noDataYet: 'Sem dados ainda',
    tapToAdd: 'Toque para adicionar',
    shared: 'Compartilhado',
    active: 'Ativo',
    level: 'Nível',
    dayStreak: 'dias consecutivos',
    completed: 'concluídos',
    badges: 'medalhas',
    xp: 'XP',
  },
  ja: {
    calendar: 'カレンダー',
    track: '追跡',
    learn: '学習',
    settings: '設定',
    morning: '朝',
    night: '夜',
    phonebook: '連絡先',
    chats: 'チャット',
    planner: 'プランナー',
    ai: 'AI',
    universe: '宇宙',
    analytics: '分析',
    thisMonth: '今月',
    events: 'イベント',
    high: '高',
    medium: '中',
    low: '低',
    noEventsForThisDay: 'この日のイベントはありません',
    tapThePlusButtonToAddOne: '+ボタンをタップして追加',
    addEvent: 'イベントを追加',
    editEvent: 'イベントを編集',
    eventTitle: 'イベントのタイトル',
    category: 'カテゴリー',
    priority: '優先度',
    time: '時間',
    description: '説明',
    work: '仕事',
    personal: '個人',
    health: '健康',
    social: '社交',
    other: 'その他',
    updateEvent: 'イベントを更新',
    deleteEvent: 'イベントを削除',
    areYouSureDeleteEvent: 'このイベントを削除してもよろしいですか？',
    cancel: 'キャンセル',
    delete: '削除',
    error: 'エラー',
    pleaseEnterEventTitle: 'イベントのタイトルを入力してください',
    addNotes: 'メモを追加...',
    selectLanguage: '言語を選択',
    chooseYourPreferredLanguage: 'ご希望の言語を選択してください',
    continue: '続ける',
    trackProgress: '進捗を追跡',
    yourFinancialJourney: 'あなたの財務の旅',
    financialOverview: '財務概要',
    income: '収入',
    expenses: '支出',
    savings: '貯蓄',
    netWorth: '純資産',
    addTransaction: '取引を追加',
    wealthManifesting: '富の引き寄せ',
    todaysManifestations: '今日の引き寄せ',
    noManifestationsYet: '今日の引き寄せはまだありません',
    addManifestation: '引き寄せを追加',
    wealthGoals: '富の目標',
    noWealthGoalsYet: '富の目標はまだありません',
    addGoal: '目標を追加',
    complete: '完了',
    metricsDashboard: 'メトリクスダッシュボード',
    trackAndAnalyze: '追跡と分析',
    passwordManager: 'パスワードマネージャー',
    secureVault: 'セキュア金庫',
    mindMapping: 'マインドマップ',
    visualizeIdeas: 'アイデアを可視化',
    riseAndShine: '起きて輝こう',
    goodMorning: 'おはようございます',
    seizeTheDay: '今日をつかもう',
    morningInspiration: '朝のインスピレーション',
    awakeningRituals: '目覚めの儀式',
    morningMeditation: '朝の瞑想',
    centerYourMind: '心を落ち着かせて深呼吸',
    morningRoutines: '朝のルーティン',
    buildYourPerfectRitual: '完璧な儀式を作ろう',
    dailyAffirmations: '毎日のアファメーション',
    speakPowerIntoExistence: '力を言葉にして存在させる',
    morningHabits: '朝の習慣',
    fuelYourTransformation: '変化の力を養う',
    wellnessCheck: 'ウェルネスチェック',
    tuneIntoYourEnergy: 'エネルギーに同調',
    embraceTheLight: '光を抱きしめて。今日を自分のものに。',
    goodEvening: 'こんばんは',
    goodNight: 'おやすみなさい',
    restWell: 'よく休んでください',
    tonightsReflection: '今夜の振り返り',
    eveningRituals: '夕方の儀式',
    momentsOfGratitude: '感謝の瞬間',
    captureYourThoughts: '考えを記録する',
    howImFeeling: '今の気持ち',
    checkInWithEmotions: '感情に向き合う',
    dreamJournal: '夢日記',
    captureYourDreams: '夢を記録する',
    sleepMeditation: '睡眠瞑想',
    peacefulRestSounds: '穏やかな休息の音',
    tomorrowsIntentions: '明日の意図',
    setGoalsForTomorrow: '明日の目標を設定',
    dailyHealthAssessment: '毎日の健康評価',
    takeYourTime: '急がないで。ゆっくりと。',
    toolsAndSettings: 'ツールと設定',
    customizeYourExperience: '体験をカスタマイズ',
    membership: 'メンバーシップ',
    premiumPlan: 'プレミアムプラン',
    activeSubscription: 'アクティブな購読',
    accountSettings: 'アカウント設定',
    manageYourAccount: 'アカウント情報を管理',
    appTour: 'アプリツアー',
    watchVideoTour: 'ビデオツアーを見てAudreyの歌を聴く',
    notifications: '通知',
    manageEventReminders: 'イベントリマインダーを管理',
    nightMode: 'ナイトモード',
    enabled: '有効',
    disabled: '無効',
    theme: 'テーマ',
    language: '言語',
    audioStyle: 'オーディオスタイル',
    sound: 'サウンド',
    muted: 'ミュート',
    unavailable: '利用不可',
    textSize: 'テキストサイズ',
    appMode: 'アプリモード',
    universeMode: '宇宙モード',
    classicMode: 'クラシックモード',
    logOut: 'ログアウト',
    signedInWithDemo: 'デモアカウントでログインしています',
    verified: '確認済み',
    autoTheme: '自動テーマ',
    autoThemeDescription: '祝日や季節に応じてテーマを自動変更',
    calendarBackgrounds: 'カレンダー背景',
    customizeCalendarAppearance: 'カレンダーの外観をカスタマイズ',
    calendarThemes: 'カレンダーテーマ',
    yourCalendars: 'あなたのカレンダー',
    colorThemes: 'カラーテーマ',
    themesAvailable: '利用可能なテーマ',
    backToTools: 'ツールに戻る',
    choosePreferredAudioStyle: 'お好みのオーディオスタイルを選択',
    chooseComfortableSize: '快適な読書サイズを選択',
    customizeAppAppearance: 'アプリの外観をカスタマイズ',
    name: '名前',
    email: 'メール',
    account: 'アカウント',
    title: 'タイトル',
    amount: '金額',
    type: 'タイプ',
    goalTitle: '目標タイトル',
    targetAmount: '目標金額',
    manifestation: '引き寄せ',
    writeYourManifestation: '引き寄せを書いてください...',
    amountOptional: '金額（任意）',
    save: '保存',
    edit: '編集',
    add: '追加',
    close: '閉じる',
    back: '戻る',
    next: '次へ',
    done: '完了',
    loading: '読み込み中...',
    success: '成功',
    pleaseWait: 'お待ちください...',
    noDataYet: 'データはまだありません',
    tapToAdd: 'タップして追加',
    shared: '共有',
    active: 'アクティブ',
    level: 'レベル',
    dayStreak: '連続日数',
    completed: '完了',
    badges: 'バッジ',
    xp: 'XP',
  },
  he: {
    calendar: 'לוח שנה',
    track: 'מעקב',
    learn: 'למידה',
    settings: 'הגדרות',
    morning: 'בוקר',
    night: 'לילה',
    phonebook: 'אנשי קשר',
    chats: 'צ\'אטים',
    planner: 'מתכנן',
    ai: 'בינה מלאכותית',
    universe: 'יקום',
    analytics: 'ניתוח',
    thisMonth: 'החודש',
    events: 'אירועים',
    high: 'גבוה',
    medium: 'בינוני',
    low: 'נמוך',
    noEventsForThisDay: 'אין אירועים ליום זה',
    tapThePlusButtonToAddOne: 'הקש על כפתור + כדי להוסיף',
    addEvent: 'הוסף אירוע',
    editEvent: 'ערוך אירוע',
    eventTitle: 'כותרת האירוע',
    category: 'קטגוריה',
    priority: 'עדיפות',
    time: 'זמן',
    description: 'תיאור',
    work: 'עבודה',
    personal: 'אישי',
    health: 'בריאות',
    social: 'חברתי',
    other: 'אחר',
    updateEvent: 'עדכן אירוע',
    deleteEvent: 'מחק אירוע',
    areYouSureDeleteEvent: 'האם אתה בטוח שברצונך למחוק אירוע זה?',
    cancel: 'ביטול',
    delete: 'מחק',
    error: 'שגיאה',
    pleaseEnterEventTitle: 'נא להזין כותרת אירוע',
    addNotes: 'הוסף הערות...',
    selectLanguage: 'בחר שפה',
    chooseYourPreferredLanguage: 'בחר את השפה המועדפת עליך',
    continue: 'המשך',
    trackProgress: 'מעקב אחר התקדמות',
    yourFinancialJourney: 'המסע הפיננסי שלך',
    financialOverview: 'סקירה פיננסית',
    income: 'הכנסה',
    expenses: 'הוצאות',
    savings: 'חסכונות',
    netWorth: 'שווי נקי',
    addTransaction: 'הוסף עסקה',
    wealthManifesting: 'ביטוי עושר',
    todaysManifestations: 'הביטויים של היום',
    noManifestationsYet: 'אין ביטויים עדיין היום',
    addManifestation: 'הוסף ביטוי',
    wealthGoals: 'מטרות עושר',
    noWealthGoalsYet: 'אין מטרות עושר עדיין',
    addGoal: 'הוסף מטרה',
    complete: 'השלם',
    metricsDashboard: 'לוח מדדים',
    trackAndAnalyze: 'עקוב ונתח',
    passwordManager: 'מנהל סיסמאות',
    secureVault: 'כספת מאובטחת',
    mindMapping: 'מיפוי מחשבות',
    visualizeIdeas: 'הדמיית רעיונות',
    riseAndShine: 'קום והאר',
    goodMorning: 'בוקר טוב',
    seizeTheDay: 'נצל את היום',
    morningInspiration: 'השראת בוקר',
    awakeningRituals: 'טקסי התעוררות',
    morningMeditation: 'מדיטציית בוקר',
    centerYourMind: 'רכז את מחשבותיך ונשום',
    morningRoutines: 'שגרות בוקר',
    buildYourPerfectRitual: 'בנה את הטקס המושלם שלך',
    dailyAffirmations: 'אישורים יומיים',
    speakPowerIntoExistence: 'דבר כוח לקיום',
    morningHabits: 'הרגלי בוקר',
    fuelYourTransformation: 'תדלק את השינוי שלך',
    wellnessCheck: 'בדיקת רווחה',
    tuneIntoYourEnergy: 'התחבר לאנרגיה שלך',
    embraceTheLight: 'חבק את האור. נצל את יומך.',
    goodEvening: 'ערב טוב',
    goodNight: 'לילה טוב',
    restWell: 'מנוחה טובה',
    tonightsReflection: 'הרהור הערב',
    eveningRituals: 'טקסי ערב',
    momentsOfGratitude: 'רגעי הכרת תודה',
    captureYourThoughts: 'לכוד את מחשבותיך',
    howImFeeling: 'איך אני מרגיש',
    checkInWithEmotions: 'התחבר לרגשות שלך',
    dreamJournal: 'יומן חלומות',
    captureYourDreams: 'לכוד את החלומות שלך',
    sleepMeditation: 'מדיטציית שינה',
    peacefulRestSounds: 'צלילי מנוחה שלווים',
    tomorrowsIntentions: 'כוונות למחר',
    setGoalsForTomorrow: 'הגדר מטרות למחר',
    dailyHealthAssessment: 'הערכת בריאות יומית',
    takeYourTime: 'קח את הזמן. אין לחץ.',
    toolsAndSettings: 'כלים והגדרות',
    customizeYourExperience: 'התאם אישית את החוויה שלך',
    membership: 'חברות',
    premiumPlan: 'תוכנית פרימיום',
    activeSubscription: 'מנוי פעיל',
    accountSettings: 'הגדרות חשבון',
    manageYourAccount: 'נהל את פרטי החשבון שלך',
    appTour: 'סיור באפליקציה',
    watchVideoTour: 'צפה בסיור וידאו והאזן לשיר של אודרי',
    notifications: 'התראות',
    manageEventReminders: 'נהל תזכורות אירועים',
    nightMode: 'מצב לילה',
    enabled: 'מופעל',
    disabled: 'מושבת',
    theme: 'ערכת נושא',
    language: 'שפה',
    audioStyle: 'סגנון שמע',
    sound: 'צליל',
    muted: 'מושתק',
    unavailable: 'לא זמין',
    textSize: 'גודל טקסט',
    appMode: 'מצב אפליקציה',
    universeMode: 'מצב יקום',
    classicMode: 'מצב קלאסי',
    logOut: 'התנתק',
    signedInWithDemo: 'אתה מחובר עם חשבון הדגמה',
    verified: 'מאומת',
    autoTheme: 'ערכת נושא אוטומטית',
    autoThemeDescription: 'שנה ערכת נושא אוטומטית לפי חגים ועונות',
    calendarBackgrounds: 'רקעי לוח שנה',
    customizeCalendarAppearance: 'התאם את מראה לוח השנה',
    calendarThemes: 'ערכות נושא ללוח שנה',
    yourCalendars: 'לוחות השנה שלך',
    colorThemes: 'ערכות צבעים',
    themesAvailable: 'ערכות נושא זמינות',
    backToTools: 'חזרה לכלים',
    choosePreferredAudioStyle: 'בחר את סגנון השמע המועדף',
    chooseComfortableSize: 'בחר גודל קריאה נוח',
    customizeAppAppearance: 'התאם את מראה האפליקציה',
    name: 'שם',
    email: 'אימייל',
    account: 'חשבון',
    title: 'כותרת',
    amount: 'סכום',
    type: 'סוג',
    goalTitle: 'כותרת מטרה',
    targetAmount: 'סכום יעד',
    manifestation: 'ביטוי',
    writeYourManifestation: 'כתוב את הביטוי שלך...',
    amountOptional: 'סכום (אופציונלי)',
    save: 'שמור',
    edit: 'ערוך',
    add: 'הוסף',
    close: 'סגור',
    back: 'חזרה',
    next: 'הבא',
    done: 'סיום',
    loading: 'טוען...',
    success: 'הצלחה',
    pleaseWait: 'אנא המתן...',
    noDataYet: 'אין נתונים עדיין',
    tapToAdd: 'הקש להוספה',
    shared: 'משותף',
    active: 'פעיל',
    level: 'רמה',
    dayStreak: 'ימים רצופים',
    completed: 'הושלם',
    badges: 'תגים',
    xp: 'נקודות ניסיון',
  },
  ro: {
    calendar: 'Calendar',
    track: 'Urmărește',
    learn: 'Învață',
    settings: 'Setări',
    morning: 'Dimineață',
    night: 'Noapte',
    phonebook: 'Contacte',
    chats: 'Conversații',
    planner: 'Planificator',
    ai: 'IA',
    universe: 'Univers',
    analytics: 'Analize',
    thisMonth: 'Luna Aceasta',
    events: 'Evenimente',
    high: 'Ridicată',
    medium: 'Medie',
    low: 'Scăzută',
    noEventsForThisDay: 'Nu există evenimente pentru această zi',
    tapThePlusButtonToAddOne: 'Apasă butonul + pentru a adăuga unul',
    addEvent: 'Adaugă Eveniment',
    editEvent: 'Editează Eveniment',
    eventTitle: 'Titlul Evenimentului',
    category: 'Categorie',
    priority: 'Prioritate',
    time: 'Oră',
    description: 'Descriere',
    work: 'Muncă',
    personal: 'Personal',
    health: 'Sănătate',
    social: 'Social',
    other: 'Altele',
    updateEvent: 'Actualizează Eveniment',
    deleteEvent: 'Șterge Eveniment',
    areYouSureDeleteEvent: 'Ești sigur că vrei să ștergi acest eveniment?',
    cancel: 'Anulează',
    delete: 'Șterge',
    error: 'Eroare',
    pleaseEnterEventTitle: 'Te rog introdu un titlu pentru eveniment',
    addNotes: 'Adaugă notițe...',
    selectLanguage: 'Selectează Limba',
    chooseYourPreferredLanguage: 'Alege limba preferată',
    continue: 'Continuă',
    trackProgress: 'Urmărește Progresul',
    yourFinancialJourney: 'Călătoria Ta Financiară',
    financialOverview: 'Prezentare Financiară',
    income: 'Venituri',
    expenses: 'Cheltuieli',
    savings: 'Economii',
    netWorth: 'Avere Netă',
    addTransaction: 'Adaugă Tranzacție',
    wealthManifesting: 'Manifestarea Bogăției',
    todaysManifestations: 'Manifestările de Azi',
    noManifestationsYet: 'Nicio manifestare încă azi',
    addManifestation: 'Adaugă Manifestare',
    wealthGoals: 'Obiective de Bogăție',
    noWealthGoalsYet: 'Niciun obiectiv de bogăție',
    addGoal: 'Adaugă Obiectiv',
    complete: 'Completează',
    metricsDashboard: 'Tablou de Metrici',
    trackAndAnalyze: 'Urmărește și Analizează',
    passwordManager: 'Manager de Parole',
    secureVault: 'Seif Securizat',
    mindMapping: 'Hărți Mentale',
    visualizeIdeas: 'Vizualizează Ideile',
    riseAndShine: 'Trezește-te și Strălucește',
    goodMorning: 'Bună Dimineața',
    seizeTheDay: 'Profită de Zi',
    morningInspiration: 'Inspirație Matinală',
    awakeningRituals: 'Ritualuri de Trezire',
    morningMeditation: 'Meditație Matinală',
    centerYourMind: 'Centrează-ți mintea și respiră',
    morningRoutines: 'Rutine Matinale',
    buildYourPerfectRitual: 'Construiește ritualul tău perfect',
    dailyAffirmations: 'Afirmații Zilnice',
    speakPowerIntoExistence: 'Vorbește putere în existență',
    morningHabits: 'Obiceiuri Matinale',
    fuelYourTransformation: 'Alimentează-ți transformarea',
    wellnessCheck: 'Verificare Wellness',
    tuneIntoYourEnergy: 'Conectează-te la energia ta',
    embraceTheLight: 'Îmbrățișează lumina. Cucerește-ți ziua.',
    goodEvening: 'Bună Seara',
    goodNight: 'Noapte Bună',
    restWell: 'Odihnă Plăcută',
    tonightsReflection: 'Reflecția de Diseară',
    eveningRituals: 'Ritualuri de Seară',
    momentsOfGratitude: 'Momente de Recunoștință',
    captureYourThoughts: 'Captează-ți gândurile',
    howImFeeling: 'Cum Mă Simt',
    checkInWithEmotions: 'Conectează-te cu emoțiile tale',
    dreamJournal: 'Jurnal de Vise',
    captureYourDreams: 'Captează-ți visele',
    sleepMeditation: 'Meditație pentru Somn',
    peacefulRestSounds: 'Sunete de odihnă liniștită',
    tomorrowsIntentions: 'Intențiile pentru Mâine',
    setGoalsForTomorrow: 'Stabilește obiective pentru mâine',
    dailyHealthAssessment: 'Evaluare zilnică a sănătății',
    takeYourTime: 'Ia-ți timpul. Nu te grăbi.',
    toolsAndSettings: 'Instrumente și Setări',
    customizeYourExperience: 'Personalizează-ți experiența',
    membership: 'Abonament',
    premiumPlan: 'Plan Premium',
    activeSubscription: 'Abonament activ',
    accountSettings: 'Setări Cont',
    manageYourAccount: 'Gestionează informațiile contului tău',
    appTour: 'Tur Aplicație',
    watchVideoTour: 'Vizionează turul video și ascultă cântecul lui Audrey',
    notifications: 'Notificări',
    manageEventReminders: 'Gestionează memento-urile evenimentelor',
    nightMode: 'Mod Noapte',
    enabled: 'Activat',
    disabled: 'Dezactivat',
    theme: 'Temă',
    language: 'Limbă',
    audioStyle: 'Stil Audio',
    sound: 'Sunet',
    muted: 'Fără sunet',
    unavailable: 'Indisponibil',
    textSize: 'Dimensiune Text',
    appMode: 'Mod Aplicație',
    universeMode: 'Mod Univers',
    classicMode: 'Mod Clasic',
    logOut: 'Deconectare',
    signedInWithDemo: 'Ești conectat cu un cont demo',
    verified: 'Verificat',
    autoTheme: 'Temă Automată',
    autoThemeDescription: 'Schimbă tema automat în funcție de sărbători și anotimpuri',
    calendarBackgrounds: 'Fundaluri Calendar',
    customizeCalendarAppearance: 'Personalizează aspectul calendarului',
    calendarThemes: 'Teme Calendar',
    yourCalendars: 'Calendarele tale',
    colorThemes: 'Teme de Culori',
    themesAvailable: 'teme disponibile',
    backToTools: 'Înapoi la Instrumente',
    choosePreferredAudioStyle: 'Alege stilul audio preferat',
    chooseComfortableSize: 'Alege o dimensiune confortabilă pentru citire',
    customizeAppAppearance: 'Personalizează aspectul aplicației',
    name: 'Nume',
    email: 'Email',
    account: 'Cont',
    title: 'Titlu',
    amount: 'Sumă',
    type: 'Tip',
    goalTitle: 'Titlu Obiectiv',
    targetAmount: 'Sumă Țintă',
    manifestation: 'Manifestare',
    writeYourManifestation: 'Scrie manifestarea ta...',
    amountOptional: 'Sumă (Opțional)',
    save: 'Salvează',
    edit: 'Editează',
    add: 'Adaugă',
    close: 'Închide',
    back: 'Înapoi',
    next: 'Următorul',
    done: 'Gata',
    loading: 'Se încarcă...',
    success: 'Succes',
    pleaseWait: 'Te rog așteaptă...',
    noDataYet: 'Nicio dată încă',
    tapToAdd: 'Apasă pentru a adăuga',
    shared: 'Partajat',
    active: 'Activ',
    level: 'Nivel',
    dayStreak: 'zile consecutive',
    completed: 'completate',
    badges: 'insigne',
    xp: 'XP',
  },
  ru: {
    calendar: 'Календарь',
    track: 'Отслеживать',
    learn: 'Учиться',
    settings: 'Настройки',
    morning: 'Утро',
    night: 'Ночь',
    phonebook: 'Контакты',
    chats: 'Чаты',
    planner: 'Планировщик',
    ai: 'ИИ',
    universe: 'Вселенная',
    analytics: 'Аналитика',
    thisMonth: 'Этот месяц',
    events: 'События',
    high: 'Высокий',
    medium: 'Средний',
    low: 'Низкий',
    noEventsForThisDay: 'Нет событий на этот день',
    tapThePlusButtonToAddOne: 'Нажмите на кнопку + чтобы добавить',
    addEvent: 'Добавить событие',
    editEvent: 'Редактировать событие',
    eventTitle: 'Название события',
    category: 'Категория',
    priority: 'Приоритет',
    time: 'Время',
    description: 'Описание',
    work: 'Работа',
    personal: 'Личное',
    health: 'Здоровье',
    social: 'Социальное',
    other: 'Другое',
    updateEvent: 'Обновить событие',
    deleteEvent: 'Удалить событие',
    areYouSureDeleteEvent: 'Вы уверены, что хотите удалить это событие?',
    cancel: 'Отмена',
    delete: 'Удалить',
    error: 'Ошибка',
    pleaseEnterEventTitle: 'Пожалуйста, введите название события',
    addNotes: 'Добавить заметки...',
    selectLanguage: 'Выбрать язык',
    chooseYourPreferredLanguage: 'Выберите предпочитаемый язык',
    continue: 'Продолжить',
    trackProgress: 'Отслеживать прогресс',
    yourFinancialJourney: 'Ваш финансовый путь',
    financialOverview: 'Финансовый обзор',
    income: 'Доход',
    expenses: 'Расходы',
    savings: 'Сбережения',
    netWorth: 'Чистая стоимость',
    addTransaction: 'Добавить транзакцию',
    wealthManifesting: 'Манифестация богатства',
    todaysManifestations: 'Сегодняшние манифестации',
    noManifestationsYet: 'Пока нет манифестаций сегодня',
    addManifestation: 'Добавить манифестацию',
    wealthGoals: 'Цели богатства',
    noWealthGoalsYet: 'Пока нет целей богатства',
    addGoal: 'Добавить цель',
    complete: 'Завершить',
    metricsDashboard: 'Панель метрик',
    trackAndAnalyze: 'Отслеживание и анализ',
    passwordManager: 'Менеджер паролей',
    secureVault: 'Безопасное хранилище',
    mindMapping: 'Ментальные карты',
    visualizeIdeas: 'Визуализация идей',
    riseAndShine: 'Вставай и сияй',
    goodMorning: 'Доброе утро',
    seizeTheDay: 'Используй день',
    morningInspiration: 'Утреннее вдохновение',
    awakeningRituals: 'Ритуалы пробуждения',
    morningMeditation: 'Утренняя медитация',
    centerYourMind: 'Сосредоточь разум и дыши',
    morningRoutines: 'Утренние рутины',
    buildYourPerfectRitual: 'Создай свой идеальный ритуал',
    dailyAffirmations: 'Ежедневные аффирмации',
    speakPowerIntoExistence: 'Говори силу в существование',
    morningHabits: 'Утренние привычки',
    fuelYourTransformation: 'Питай свою трансформацию',
    wellnessCheck: 'Проверка здоровья',
    tuneIntoYourEnergy: 'Настройся на свою энергию',
    embraceTheLight: 'Прими свет. Владей своим днём.',
    goodEvening: 'Добрый вечер',
    goodNight: 'Спокойной ночи',
    restWell: 'Хорошего отдыха',
    tonightsReflection: 'Вечернее размышление',
    eveningRituals: 'Вечерние ритуалы',
    momentsOfGratitude: 'Моменты благодарности',
    captureYourThoughts: 'Запиши свои мысли',
    howImFeeling: 'Как я себя чувствую',
    checkInWithEmotions: 'Связь с эмоциями',
    dreamJournal: 'Дневник снов',
    captureYourDreams: 'Запиши свои сны',
    sleepMeditation: 'Медитация для сна',
    peacefulRestSounds: 'Звуки спокойного отдыха',
    tomorrowsIntentions: 'Намерения на завтра',
    setGoalsForTomorrow: 'Установи цели на завтра',
    dailyHealthAssessment: 'Ежедневная оценка здоровья',
    takeYourTime: 'Не торопись. Спешить некуда.',
    toolsAndSettings: 'Инструменты и настройки',
    customizeYourExperience: 'Настрой свой опыт',
    membership: 'Членство',
    premiumPlan: 'Премиум план',
    activeSubscription: 'Активная подписка',
    accountSettings: 'Настройки аккаунта',
    manageYourAccount: 'Управляй информацией аккаунта',
    appTour: 'Тур по приложению',
    watchVideoTour: 'Смотри видео тур и слушай песню Одри',
    notifications: 'Уведомления',
    manageEventReminders: 'Управляй напоминаниями событий',
    nightMode: 'Ночной режим',
    enabled: 'Включено',
    disabled: 'Отключено',
    theme: 'Тема',
    language: 'Язык',
    audioStyle: 'Стиль аудио',
    sound: 'Звук',
    muted: 'Без звука',
    unavailable: 'Недоступно',
    textSize: 'Размер текста',
    appMode: 'Режим приложения',
    universeMode: 'Режим вселенной',
    classicMode: 'Классический режим',
    logOut: 'Выйти',
    signedInWithDemo: 'Вы вошли с демо аккаунтом',
    verified: 'Подтверждено',
    autoTheme: 'Авто тема',
    autoThemeDescription: 'Автоматическая смена темы по праздникам и сезонам',
    calendarBackgrounds: 'Фоны календаря',
    customizeCalendarAppearance: 'Настрой внешний вид календаря',
    calendarThemes: 'Темы календаря',
    yourCalendars: 'Твои календари',
    colorThemes: 'Цветовые темы',
    themesAvailable: 'доступных тем',
    backToTools: 'Назад к инструментам',
    choosePreferredAudioStyle: 'Выбери предпочитаемый стиль аудио',
    chooseComfortableSize: 'Выбери комфортный размер для чтения',
    customizeAppAppearance: 'Настрой внешний вид приложения',
    name: 'Имя',
    email: 'Email',
    account: 'Аккаунт',
    title: 'Название',
    amount: 'Сумма',
    type: 'Тип',
    goalTitle: 'Название цели',
    targetAmount: 'Целевая сумма',
    manifestation: 'Манифестация',
    writeYourManifestation: 'Напиши свою манифестацию...',
    amountOptional: 'Сумма (необязательно)',
    save: 'Сохранить',
    edit: 'Редактировать',
    add: 'Добавить',
    close: 'Закрыть',
    back: 'Назад',
    next: 'Далее',
    done: 'Готово',
    loading: 'Загрузка...',
    success: 'Успех',
    pleaseWait: 'Пожалуйста, подождите...',
    noDataYet: 'Пока нет данных',
    tapToAdd: 'Нажми для добавления',
    shared: 'Общий',
    active: 'Активный',
    level: 'Уровень',
    dayStreak: 'дней подряд',
    completed: 'завершено',
    badges: 'значки',
    xp: 'XP',
  },
  hi: {
    calendar: 'कैलेंडर',
    track: 'ट्रैक',
    learn: 'सीखें',
    settings: 'सेटिंग्स',
    morning: 'सुबह',
    night: 'रात',
    phonebook: 'संपर्क',
    chats: 'चैट',
    planner: 'प्लानर',
    ai: 'एआई',
    universe: 'ब्रह्मांड',
    analytics: 'विश्लेषण',
    thisMonth: 'यह महीना',
    events: 'घटनाएँ',
    high: 'उच्च',
    medium: 'मध्यम',
    low: 'कम',
    noEventsForThisDay: 'इस दिन के लिए कोई घटना नहीं',
    tapThePlusButtonToAddOne: 'जोड़ने के लिए + बटन दबाएं',
    addEvent: 'घटना जोड़ें',
    editEvent: 'घटना संपादित करें',
    eventTitle: 'घटना का शीर्षक',
    category: 'श्रेणी',
    priority: 'प्राथमिकता',
    time: 'समय',
    description: 'विवरण',
    work: 'काम',
    personal: 'व्यक्तिगत',
    health: 'स्वास्थ्य',
    social: 'सामाजिक',
    other: 'अन्य',
    updateEvent: 'घटना अपडेट करें',
    deleteEvent: 'घटना हटाएं',
    areYouSureDeleteEvent: 'क्या आप वाकई इस घटना को हटाना चाहते हैं?',
    cancel: 'रद्द करें',
    delete: 'हटाएं',
    error: 'त्रुटि',
    pleaseEnterEventTitle: 'कृपया घटना का शीर्षक दर्ज करें',
    addNotes: 'नोट्स जोड़ें...',
    selectLanguage: 'भाषा चुनें',
    chooseYourPreferredLanguage: 'अपनी पसंदीदा भाषा चुनें',
    continue: 'जारी रखें',
    trackProgress: 'प्रगति ट्रैक करें',
    yourFinancialJourney: 'आपकी वित्तीय यात्रा',
    financialOverview: 'वित्तीय अवलोकन',
    income: 'आय',
    expenses: 'खर्च',
    savings: 'बचत',
    netWorth: 'कुल संपत्ति',
    addTransaction: 'लेनदेन जोड़ें',
    wealthManifesting: 'धन प्रकटीकरण',
    todaysManifestations: 'आज के प्रकटीकरण',
    noManifestationsYet: 'आज कोई प्रकटीकरण नहीं',
    addManifestation: 'प्रकटीकरण जोड़ें',
    wealthGoals: 'धन लक्ष्य',
    noWealthGoalsYet: 'कोई धन लक्ष्य नहीं',
    addGoal: 'लक्ष्य जोड़ें',
    complete: 'पूर्ण',
    metricsDashboard: 'मेट्रिक्स डैशबोर्ड',
    trackAndAnalyze: 'ट्रैक और विश्लेषण',
    passwordManager: 'पासवर्ड मैनेजर',
    secureVault: 'सुरक्षित तिजोरी',
    mindMapping: 'माइंड मैपिंग',
    visualizeIdeas: 'विचारों को देखें',
    riseAndShine: 'उठो और चमको',
    goodMorning: 'सुप्रभात',
    seizeTheDay: 'दिन को अपनाओ',
    morningInspiration: 'सुबह की प्रेरणा',
    awakeningRituals: 'जागने के अनुष्ठान',
    morningMeditation: 'सुबह का ध्यान',
    centerYourMind: 'अपने मन को केंद्रित करें और सांस लें',
    morningRoutines: 'सुबह की दिनचर्या',
    buildYourPerfectRitual: 'अपना आदर्श अनुष्ठान बनाएं',
    dailyAffirmations: 'दैनिक पुष्टिकरण',
    speakPowerIntoExistence: 'शक्ति को बोलें और अस्तित्व में लाएं',
    morningHabits: 'सुबह की आदतें',
    fuelYourTransformation: 'अपने परिवर्तन को शक्ति दें',
    wellnessCheck: 'स्वास्थ्य जांच',
    tuneIntoYourEnergy: 'अपनी ऊर्जा से जुड़ें',
    embraceTheLight: 'प्रकाश को अपनाएं। अपना दिन जीतें।',
    goodEvening: 'शुभ संध्या',
    goodNight: 'शुभ रात्रि',
    restWell: 'अच्छे से आराम करें',
    tonightsReflection: 'आज रात का चिंतन',
    eveningRituals: 'शाम के अनुष्ठान',
    momentsOfGratitude: 'कृतज्ञता के क्षण',
    captureYourThoughts: 'अपने विचार लिखें',
    howImFeeling: 'मैं कैसा महसूस कर रहा हूं',
    checkInWithEmotions: 'अपनी भावनाओं से जुड़ें',
    dreamJournal: 'स्वप्न डायरी',
    captureYourDreams: 'अपने सपने लिखें',
    sleepMeditation: 'नींद का ध्यान',
    peacefulRestSounds: 'शांतिपूर्ण आराम की आवाज़ें',
    tomorrowsIntentions: 'कल के इरादे',
    setGoalsForTomorrow: 'कल के लिए लक्ष्य निर्धारित करें',
    dailyHealthAssessment: 'दैनिक स्वास्थ्य मूल्यांकन',
    takeYourTime: 'अपना समय लें। कोई जल्दी नहीं है।',
    toolsAndSettings: 'उपकरण और सेटिंग्स',
    customizeYourExperience: 'अपना अनुभव अनुकूलित करें',
    membership: 'सदस्यता',
    premiumPlan: 'प्रीमियम योजना',
    activeSubscription: 'सक्रिय सदस्यता',
    accountSettings: 'खाता सेटिंग्स',
    manageYourAccount: 'अपने खाते की जानकारी प्रबंधित करें',
    appTour: 'ऐप टूर',
    watchVideoTour: 'वीडियो टूर देखें और ऑड्रे का गाना सुनें',
    notifications: 'सूचनाएं',
    manageEventReminders: 'इवेंट रिमाइंडर प्रबंधित करें',
    nightMode: 'नाइट मोड',
    enabled: 'सक्षम',
    disabled: 'अक्षम',
    theme: 'थीम',
    language: 'भाषा',
    audioStyle: 'ऑडियो स्टाइल',
    sound: 'ध्वनि',
    muted: 'म्यूट',
    unavailable: 'अनुपलब्ध',
    textSize: 'टेक्स्ट साइज़',
    appMode: 'ऐप मोड',
    universeMode: 'यूनिवर्स मोड',
    classicMode: 'क्लासिक मोड',
    logOut: 'लॉग आउट',
    signedInWithDemo: 'आप डेमो अकाउंट से लॉग इन हैं',
    verified: 'सत्यापित',
    autoTheme: 'ऑटो थीम',
    autoThemeDescription: 'त्योहारों और मौसमों के अनुसार थीम स्वचालित रूप से बदलें',
    calendarBackgrounds: 'कैलेंडर बैकग्राउंड',
    customizeCalendarAppearance: 'अपने कैलेंडर का रूप अनुकूलित करें',
    calendarThemes: 'कैलेंडर थीम',
    yourCalendars: 'आपके कैलेंडर',
    colorThemes: 'रंग थीम',
    themesAvailable: 'थीम उपलब्ध',
    backToTools: 'उपकरणों पर वापस',
    choosePreferredAudioStyle: 'अपनी पसंदीदा ऑडियो स्टाइल चुनें',
    chooseComfortableSize: 'आरामदायक पढ़ने का आकार चुनें',
    customizeAppAppearance: 'ऐप का रूप अनुकूलित करें',
    name: 'नाम',
    email: 'ईमेल',
    account: 'खाता',
    title: 'शीर्षक',
    amount: 'राशि',
    type: 'प्रकार',
    goalTitle: 'लक्ष्य शीर्षक',
    targetAmount: 'लक्ष्य राशि',
    manifestation: 'प्रकटीकरण',
    writeYourManifestation: 'अपना प्रकटीकरण लिखें...',
    amountOptional: 'राशि (वैकल्पिक)',
    save: 'सहेजें',
    edit: 'संपादित करें',
    add: 'जोड़ें',
    close: 'बंद करें',
    back: 'वापस',
    next: 'आगे',
    done: 'हो गया',
    loading: 'लोड हो रहा है...',
    success: 'सफलता',
    pleaseWait: 'कृपया प्रतीक्षा करें...',
    noDataYet: 'अभी कोई डेटा नहीं',
    tapToAdd: 'जोड़ने के लिए टैप करें',
    shared: 'साझा',
    active: 'सक्रिय',
    level: 'स्तर',
    dayStreak: 'लगातार दिन',
    completed: 'पूर्ण',
    badges: 'बैज',
    xp: 'XP',
  },
};

const STORAGE_KEY = 'app_language';

export const [LanguageProvider, useLanguage] = createContextHook(() => {
  const [language, setLanguageState] = useState<Language>('en');
  const [isLoading, setIsLoading] = useState(false);
  const loadedRef = useRef(false);

  useEffect(() => {
    if (loadedRef.current) return;
    loadedRef.current = true;
    
    const loadLanguage = async () => {
      try {
        const storedLanguage = await AsyncStorage.getItem(STORAGE_KEY);
        if (storedLanguage && 
            storedLanguage !== 'undefined' && 
            storedLanguage !== 'null' && 
            !storedLanguage.includes('[object')) {
          let lang: string;
          try {
            const decrypted = await decrypt(storedLanguage);
            lang = decrypted;
          } catch {
            lang = storedLanguage;
          }
          
          if (translations[lang as Language]) {
            setLanguageState(lang as Language);
          }
        } else {
          let deviceLocale = 'en';
          
          if (Platform.OS === 'web' && typeof navigator !== 'undefined') {
            deviceLocale = navigator.language || 'en';
          }
          
          const deviceLang = deviceLocale.toLowerCase().substring(0, 2);
          const supportedLang = translations[deviceLang as Language] ? (deviceLang as Language) : 'en';
          setLanguageState(supportedLang);
        }
      } catch (error) {
        console.error('Error loading language:', error);
      }
    };
    
    loadLanguage();
  }, []);

  const setLanguage = useCallback(async (lang: Language) => {
    try {
      const encrypted = await encrypt(lang);
      await AsyncStorage.setItem(STORAGE_KEY, encrypted);
      setLanguageState(lang);
    } catch (error) {
      console.error('Error saving language:', error);
      setLanguageState(lang);
    }
  }, []);

  const t = translations[language];

  return useMemo(() => ({
    language,
    setLanguage,
    t,
    isLoading,
  }), [language, setLanguage, t, isLoading]);
});
